description = "Kendra Build KBB Workflow: agent"
prompt = """
IT IS CRITICAL THAT YOU FOLLOW THIS COMMAND: LOAD the FULL @{_kbuild/kbb/workflows/agent/workflow.md}, READ its entire contents and follow its directions exactly!
"""
