description = "Kendra Build KBB Workflow: module"
prompt = """
IT IS CRITICAL THAT YOU FOLLOW THIS COMMAND: LOAD the FULL @{_kbuild/kbb/workflows/module/workflow.md}, READ its entire contents and follow its directions exactly!
"""
